BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        id: delete_text
        text: 'Clear'
        font_size: 42
        on_press: app.clear_button()
    TextInput:
        id: input_name
        text: ''
        font_size: 42
    Button:
        text: 'Greet'
        on_press: app.handle_greet()
        font_size: 42
    Label:
        id: output_label
        font_size: 42
        color: (1, 1, 0, 1)
